feat(backend): untagged 조회 추가
woowacourse-teams/2020-taggle pull request #156
Opened 2020-08-17 03:51 UTC by kimevanjunseok

resolve #153

2020-08-17 11:11 UTC, KS-KIM commented on backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagController.java
> +    public ResponseEntity<TagBookmarkResponse> findUntagged(@AuthenticationPrincipal final SessionUser user) {
```suggestion
    public ResponseEntity<TagBookmarkResponse> findUntaggedBookmarks(@AuthenticationPrincipal final SessionUser user) {
```
이렇게 바꾸는걸 제안하려고 보니 차라리 BookmarkController에 두고 `bookmarks/untagged` URI를 가지는게 더 자연스러운 것 같은데 어떻게 생각하시나요?

2020-08-17 11:12 UTC, KS-KIM commented on backend/web/src/test/java/com/woowacourse/taggle/tag/controller/TagControllerTest.java
> +    void findUntagged() throws Exception {
```suggestion
    void findUntaggedBookmarks() throws Exception {
```

2020-08-17 11:18 UTC, KS-KIM commented on backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagController.java
> +    @GetMapping("/untagged")
```suggestion
    @GetMapping("/untagged/bookmarks")
```

2020-08-17 11:50 UTC, taejinseok commented on backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagController.java
> +    public ResponseEntity<TagBookmarkResponse> findUntagged(@AuthenticationPrincipal final SessionUser user) {
결정이 쉽지가 않네요 한번 같이 이야기해봐도 좋을거 같아요

2020-08-20 07:45 UTC, taejinseok requested changes
일부 기능에 대한 컨트롤러, 서비스를 옮기면서 가장 힘들 수 있는 인수 테스트를 포함한 각종 테스트 리팩토링까지 하느라 정말 고생 많으셨습니다. 

귀찮을 수도 있었겠지만 매번 고생해주신 덕분에 리팩토링한 테스트 코드를 보면서 도메인, 로직을 빠르게 파악할 수 있어 수월하게 리뷰를 남길 수 있었네요 😀

간략한 코멘트 남겨놓았으니 확인 부탁드려요!

2020-08-20 07:45 UTC, taejinseok commented on backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java
> +        assertThat(mockMvcResponse.statusCode()).isEqualTo(HttpStatus.NOT_FOUND.value());
삭제된 리소스의 Get 요청시 Status code 404를 반환함을 이용한 편의 메서드인것 같네요! 
이 방법으로 보다 명시적으로 리소스가 삭제 여부를 테스트 할수 있어 보입니다!

다만 `findBookmarksOfTagNotFoundException`  status code 404 여부를 확인하고 있으며, 
line 40에 assert 문에서도 404 여부를 체크함으로써 두군데서 404 여부를 중복으로 체크하는 것으로 보이네요. 

`findBookmarksOfTagNotFoundException` 메서드에서 status code 404 검사를 제거하고  Response만 반환하도록 바꿔보는건 어떨까요?

2020-08-20 08:07 UTC, ksy90101 approved these changes
다른분들이 꼼꼼하게 잘 해주셨네요! 저는 간단한 피드백을 남겼습니다~

2020-08-20 08:07 UTC, ksy90101 commented on backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
> +        final BookmarkCreateDto bookmarkCreateRequest = new BookmarkCreateDto("https://taggle.co.kr", "title",
여기도 혹시 모를 에러를 위해 정확한 URL을 적어주면 좋을거 같아요!

2020-08-20 08:07 UTC, ksy90101 commented on backend/web/src/main/java/com/woowacourse/taggle/tag/controller/TagBookmarkController.java
> +    @GetMapping("/tags/untagged/bookmarks")
untagged가 URL에 들어가니 명사가 아니여서 조금 어색하네요.. ㅎㅎ 포켓에 untagged URL을 참고하셔서 변경하실꺼면 변경하셔도 되고 그대로 둬도 괜찮을꺼 같아요!
`https://app.getpocket.com/tags/untagged-items/all`

2020-08-20 08:35 UTC, kimevanjunseok commented on backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
> +    @DisplayName("findBookmarksOfTag: 특정 태그의 북마크를 조회한다.")
놓치고 있던 부분인데 감사합니다!! 테스트가 많다 보니 못 본것이 있네요 😭😭

2020-08-20 08:46 UTC, kimevanjunseok commented on backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
> +        final BookmarkCreateDto bookmarkCreateRequest = new BookmarkCreateDto("https://taggle.co.kr", "title",
크롤링하는 부분이 아니고 테스트에서 직접 필드를 입력하고 있어서 에러는 안 날것 같습니다!!! 하지만 정확한 URL로 바꿨습니다 😊😊

2020-08-20 08:58 UTC, kimevanjunseok commented on backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java
> +        assertThat(mockMvcResponse.statusCode()).isEqualTo(HttpStatus.NOT_FOUND.value());
그렇네요!! 제가 두번하고 있네요. 동글님 피드백을 반영하여 
```java
public ExtractableResponse<MockMvcResponse> getExtractableResponse(final String path) {
    return
            given()
                    .accept(MediaType.APPLICATION_JSON_VALUE)
                    .when()
                    .get(path)
                    .then()
                    .log().all()
                    .extract();
}
```
이렇게 수정 후 assertThat으로 404를 검사하게 수정했습니다!!

2020-08-20 09:06 UTC, kimevanjunseok commented on backend/web/src/test/java/com/woowacourse/taggle/acceptance/TagAcceptanceTest.java
>      @WithMockUser(username = "tigger", password = "tigger", roles = "ADMIN")
레거시였군요!!! 말씀하신 것처럼 mocking하기 때문에 해당 부분을 제거해도 테스트 성공합니다!!! 피드백 반영하였습니다!!

2020-08-20 10:02 UTC, taejinseok approved these changes
빠른 피드백 반영 감사합니다. 다시 approve 할게요 👍

2020-08-21 08:00 UTC, KS-KIM commented on backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagBookmarkService.java
> +    public TagBookmarkResponse findBookmarksOfUntagged(final SessionUser user) {
```suggestion
    public TagBookmarkResponse findBookmarksByUser(final SessionUser user) {
```
이게 더 낫지 않을까요?

2020-08-21 08:01 UTC, KS-KIM commented on backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagBookmarkService.java
> +    public BookmarkTagResponse findTagsOfBookmark(final SessionUser user, final Long id) {
```suggestion
    public BookmarkTagResponse findTagsByBookmarkId(final SessionUser user, final Long id) {
```
이게 더 낫지 않을까요?

2020-08-21 08:42 UTC, kimevanjunseok commented on backend/core/src/main/java/com/woowacourse/taggle/tag/service/TagBookmarkService.java
> +    public TagBookmarkResponse findBookmarksOfUntagged(final SessionUser user) {
말씀하신 `findUntaggedBookmarks`로 수정했습니다.😊😊

2020-08-21 08:57 UTC, merged