feat(opengraph): 오픈그래프 이미지가 없을 경우 기본 이미지를 설정할 수 있도록 한다. (#169)
woowacourse-teams/2020-taggle pull request #170
Opened 2020-08-20 14:31 UTC by ksy90101

resolve #169

2020-08-20 17:47 UTC, taejinseok requested changes
일부 코멘트 남겨놓았어요. 확인해주세요~

2020-08-20 17:47 UTC, taejinseok commented on backend/open-graph-api/src/test/java/com/woowacourse/taggle/crawler/OpenGraphCrawlerTest.java
>      @DisplayName("extractPreview: 잘못된 url이 들어왔을 경우 예외처")
예외처리!

2020-08-20 17:47 UTC, taejinseok commented on backend/open-graph-api/src/test/java/com/woowacourse/taggle/crawler/OpenGraphCrawlerTest.java
> +                "https://lh3.googleusercontent.com/proxy/fFK04pFoxl4RBXgnvtpNYZgSIOST8suUpzhcyoXtMSi3XxrUeTnNKpqZeONXJD0hiuZWNpO1xz2_T5A0e6fG0Q-xkSVlZhiZK5fdXxAuOjGk8HFLPQ");
기본 이미지 url 체크 해주세요! 403이 발생하네요!

2020-08-20 17:47 UTC, taejinseok commented on backend/web/src/main/java/com/woowacourse/taggle/config/CrawlerConfig.java
> +    private final static String DEFAULT_IMAGE = "https://lh3.googleusercontent.com/proxy/fFK04pFoxl4RBXgnvtpNYZgSIOST8suUpzhcyoXtMSi3XxrUeTnNKpqZeONXJD0hiuZWNpO1xz2_T5A0e6fG0Q-xkSVlZhiZK5fdXxAuOjGk8H
마찬가지로 403!

2020-08-20 19:47 UTC, Ramen6315 approved these changes
고생 많으셨습니다.

동글과 같은 의견이라 바로 approve 하겠습니다.

2020-08-21 02:20 UTC, kimevanjunseok commented on backend/web/src/test/java/com/woowacourse/taggle/tag/service/BookmarkCreateServiceTest.java
> +    public static final User DEFAULT_USER = User.builder()
UserSetup을 안 쓰신 이유가 있나요?

2020-08-21 02:23 UTC, kimevanjunseok commented on backend/web/src/main/java/com/woowacourse/taggle/tag/service/BookmarkCreateService.java
> +public class BookmarkCreateService {
멀티모듈 web에 Service가 있는 게 저만 어색한가요? 이유가 있을까요?

2020-08-21 05:50 UTC, KS-KIM commented on backend/web/src/main/java/com/woowacourse/taggle/tag/service/BookmarkCreateService.java
> +public class BookmarkCreateService {
원래 web에 많이 둡니다...

2020-08-21 06:01 UTC, KS-KIM commented on backend/open-graph-api/src/main/java/com/woowacourse/taggle/crawler/OpenGraphCrawler.java
> +            String description = document.select(META_DESCRIPTION).attr(CONTENT);
가독성과 다른 메서드와의 일관성을 위해 메서드로 분리해보는건 어떨까요?
```suggestion
            String description = getDescription(document);
```

2020-08-21 06:03 UTC, KS-KIM commented on backend/open-graph-api/src/test/java/com/woowacourse/taggle/crawler/OpenGraphCrawlerTest.java
>                  .isEqualTo("https://github.githubassets.com/images/modules/open_graph/github-logo.png");
github 사이트가 변경된다면 받아오는 이미지의 url, title, description이 변경될 수 있을 것 같아요. 그럼 테스트가 깨지겠죠?!
그렇다면 과연 이를 위와 같이 직접 테스트하는게 옳을까요?
저는 이처럼 외부 의존성을 크게 가지는 부분에 대해서는 mock처리를 해야 한다고 생각하는데, 럿고의 의견은 어떤지 궁금합니다!

2020-08-21 06:04 UTC, KS-KIM commented on backend/open-graph-api/src/test/java/com/woowacourse/taggle/crawler/OpenGraphCrawlerTest.java
>                  .isEqualTo("https://github.githubassets.com/images/modules/open_graph/github-logo.png");
위 리뷰는 아래 테스트에도 해당됩니다!

2020-08-21 06:09 UTC, kimevanjunseok commented on backend/web/src/main/java/com/woowacourse/taggle/tag/service/BookmarkCreateService.java
> +public class BookmarkCreateService {
저희는 service 전부 core에 있어서 어색했나봅니다!!!

2020-08-24 08:51 UTC, KS-KIM approved these changes
마지막 코멘트 달고 approve 합니다.

단순히 crawler라고 하면 다른 crawler가 생겼을 때 헷갈릴 수 있을 것 같아요.

그러니 link-preview-crawler같은 네이밍은 어떨까요?

강제되는 사항은 아니니 고민은 해보셨으면 좋겠어요:)

2020-08-24 10:46 UTC, merged

2020-08-24 10:47 UTC, KS-KIM commented
모듈 네이밍과 관련된 사항은 당장 문제되는 부분은 아니니 조금 더 논의해보는걸로 합시다.
우선 머지했습니다.