feat(backend): develop서버 로그 설정 (#165)
woowacourse-teams/2020-taggle pull request #187
Opened 2020-08-25 10:36 UTC by Ramen6315

resolve #165

2020-08-25 10:39 UTC, ksy90101 requested changes
피드백 하나 남겼습니다!

2020-08-25 10:39 UTC, ksy90101 commented on backend/web/src/main/resources/application.yml
> +            sql: trace
이 부분은 config에 있는걸로 알고 잇는데요. 개인적으로 모두 공통적으로 사용될거 같아서, 중복 제거를 위해 공통으로 빼보는걸 추천드려요~

2020-08-25 10:50 UTC, taejinseok approved these changes
럿고의 의견에 덧대어 제 생각도 남겨놓았어요. 고생많았습니다.

2020-08-25 10:50 UTC, taejinseok commented on backend/web/src/main/resources/logback-local.xml
> -            <pattern>hello%-5level %d{HH:mm:ss.SSS} [%thread] %logger{36} - %msg [%mdc]%n</pattern>
드디어 hello가 사라졌군요 ...

2020-08-25 10:50 UTC, taejinseok commented on backend/web/src/main/resources/application.yml
> +            sql: trace
sql문과 함께 값(타입)을 찍어주는 로깅 설정인데 application-db.yml에 local쪽으로  빼는게 맞지 않을까 싶네요~

2020-08-25 12:28 UTC, kimevanjunseok approved these changes
다른 분들이 남긴 피드백과 크게 다르지 않습니다!!!
저는 approve 하겠습니다!!

2020-08-25 13:37 UTC, KS-KIM approved these changes
고생하셨습니다 💯💯

2020-08-26 04:30 UTC, ksy90101 approved these changes

2020-08-26 04:30 UTC, merged