feat(frontend): 태그 검색 기능 구현 (#160)
woowacourse-teams/2020-taggle pull request #191
Opened 2020-08-26 12:03 UTC by ksy90101

resovles #160 

- getter에 대한 이름을 추천해주세요~ ㅎㅎㅎㅎㅎ

2020-08-26 13:59 UTC, taejinseok reviewed
개인적인 생각 남겨놨어요! 확인 부탁드려요~

2020-08-26 13:59 UTC, taejinseok commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +};
여기파일 보시면 됩니다. 리뷰어님들!

2020-08-26 13:59 UTC, taejinseok commented on backend/web/src/frontend/src/views/header/component/TagNavigation.vue
> +</script>
이 파일 보시면 됩니다! 리뷰어님들!

2020-08-26 13:59 UTC, taejinseok commented on backend/web/src/frontend/src/store/modules/category.js
> +  },
이 파일 보시면 됩니다. 리뷰어님들!

2020-08-26 13:59 UTC, taejinseok commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +    },
아래처럼 사용한다면, TOTAL_CATEGORIES와 SEARCHED_CATEGORIES를 구분해서 getter를 따로 만들 필요가 없을 것이고, computed에서 드러나있는 세부 구현 내용을 category의 getter하나안에 캡슐화 할수 있을 것 같아요.

```suggestion
// @/store/modules/category.js
// ...

const getters = {
  [SEARCHED_CATEGORIES](state) => (searchKeyword) => {
    if (!searchKeyword) {
        return state.categories;
    }
    const totalCategories = JSON.parse(JSON.stringify(state.categories));
    totalCategories.forEach((category) => {
            category.tags = category.tags.filter(
                (tag) => tag.name.includes(searchKeyword));
    });

    return totalCategories;
  },
};

```

2020-08-26 14:55 UTC, ksy90101 commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +    },
이걸 고민안한게 아닌데 이렇게 getter를 사용해도될지.......ㅎㅎㅎ

2020-08-26 15:59 UTC, Ramen6315 requested changes
코드 구현 하느라 고생 많으셨습니다.

더좋은 제안 보단 궁금한점에 대한 생각을 적었어요(제가 잘 못 짚었을 수 도 있습니다)!

양해 부탁드리겠습니다. ㅎㅎ. 
감사합니다 !

2020-08-26 15:59 UTC, Ramen6315 commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +    },
@taejinseok 
이부분에 대해서 궁금한게 있는데 
getter 라는 naming만보면 그냥 값을 가져오는느낌인데 조건에 따라 return 을 다르게 가져오는 형태가 괜찮은지 궁금해요!
naming 을 잘하는건 아니지만..
searchKeyword 에 따라 categories값이 return 되니까 
제 의견은 getCategoriesBySearchKeyword 처럼 안의 로직을 어느정도 예상할 수 있는 naming이 좋지 않을까 하는생각입니다.
어떻게 생각하시는지 궁금해요!

2020-08-26 16:09 UTC, Ramen6315 requested changes

2020-08-26 16:09 UTC, Ramen6315 commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +    },
@taejinseok
이부분에 대해서 궁금한게 있는데
getter 라는 naming만보면 그냥 값을 가져오는느낌인데 조건에 따라 return 을 다르게 가져오는 형태가 괜찮은지 궁금해요!
naming 을 잘하는건 아니지만..
searchKeyword 에 따라 categories값이 return 되니까
제 의견은 getCategoriesBySearchKeyword 처럼 안의 로직을 어느정도 예상할 수 있는 naming이 좋지 않을까 하는생각입니다.
어떻게 생각하시는지 궁금해요!

2020-08-26 17:46 UTC, KS-KIM requested changes
간단히 리뷰 남깁니다.
좀 오래된 커밋내역이 보이는데, 브랜치 정리 한번 부탁드립니다.
처음에 따르기로 했던 git-flow 브랜칭 관리 전략을 지키지 못한 부분이 아쉽네요.
이외의 부분은 코드에 코멘트 남겨두었으니 확인해보시고 궁금한 점 있으시면 DM주세요:)

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/category/CategoryAddModal.vue
> +        this[SHOW_SNACKBAR](MESSAGES.CATEGORY.ADD.FAIL);
```suggestion
        await this.createCategory(this.createCategoryRequest);
        await this.fetchCategories();
        this.showSnackbar(MESSAGES.CATEGORY.ADD.SUCCESS);
      } catch (e) {
        this.showSnackbar(MESSAGES.CATEGORY.ADD.FAIL);
```
이렇게 해도 정상적으로 동작하는데, 위와 같이 작성하신 특별한 이유가 있나요?

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/category/CategoryContextMenu.vue
> +        this[SHOW_SNACKBAR](MESSAGES.CATEGORY.DELETE.FAIL);
```suggestion
        await this.deleteCategory(this.category.id);
        await this.fetchCategories();
        this.showSnackbar(MESSAGES.CATEGORY.DELETE.SUCCESS);
      } catch {
        this.showSnackbar(MESSAGES.CATEGORY.DELETE.FAIL);
```
이렇게 해도 정상적으로 동작하는데, 위와 같이 작성하신 특별한 이유가 있나요?

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/CategoryGroup.vue
> +        this[SHOW_SNACKBAR](MESSAGES.CATEGORY.EDIT.FAIL);
```suggestion
        await this.fetchCategories({ id: this.category.id, title: this.title });
        await this.fetchCategories();
        this.showSnackbar(MESSAGES.CATEGORY.EDIT.SUCCESS);
      } catch (e) {
        this.showSnackbar(MESSAGES.CATEGORY.EDIT.FAIL);
```
이렇게 해도 정상적으로 동작하는데, 위와 같이 작성하신 특별한 이유가 있나요?

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/TagEditModal.vue
> +        this[SHOW_SNACKBAR](MESSAGES.TAG.EDIT.FAIL);
```suggestion
        await this.editTag(tagId, added.element.id);
        this.showSnackbar(MESSAGES.TAG.EDIT.SUCCESS);
      } catch (e) {
        this.showSnackbar(MESSAGES.TAG.EDIT.FAIL);
```
이렇게 해도 정상적으로 동작하는데, 위와 같이 작성하신 특별한 이유가 있나요?

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +      return this[SEARCHED_CATEGORIES](this.searchKeyword);
```suggestion
      if (this.searchKeyword === '') {
        return this.totalCategories;
      }
      return this.searchedCategories(this.searchKeyword);
```

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +    this[FETCH_CATEGORIES]();
```suggestion
    this.fetchCategories();
```

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/category/CategoryEditModal.vue
> +        this[SHOW_SNACKBAR](MESSAGES.CATEGORY.EDIT.FAIL);
```suggestion
        await this.editCategory(this.category);
        await this.fetchCategories();
        this.showSnackbar(MESSAGES.CATEGORY.EDIT.SUCCESS);
        this.dialog = false;
      } catch (e) {
        this.showSnackbar(MESSAGES.CATEGORY.EDIT.FAIL);
```

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/TagNavigationBody.vue
> +</script>
```suggestion
</script>

<style>
.v-list {
  padding: 0 !important;
}
</style>
```
태그 목록이 두꺼워서 padding을 제거해줘도 좋을 것 같아요

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/category/CategoryIcons.vue
> +      await this[FETCH_CATEGORIES]();
```suggestion
        await this.deleteCategory(this.category.id);
        await this.fetchCategory();
        this.showSnackbar(MESSAGES.CATEGORY.DELETE.SUCCESS);
      } catch {
        this.showSnackbar(MESSAGES.CATEGORY.DELETE.FAIL);
      }
    },
    async fetchCategory() {
      await this.fetchCategories();
```

2020-08-26 17:46 UTC, KS-KIM commented on backend/web/src/frontend/src/views/header/component/category/TagContextMenu.vue
> +        this[SHOW_SNACKBAR](MESSAGES.TAG.DELETE.FAIL);
```suggestion
        await this.fetchCategories();
        this.showSnackbar(MESSAGES.TAG.DELETE.SUCCESS);
      } catch {
        this.showSnackbar(MESSAGES.TAG.DELETE.FAIL);
```

2020-08-27 06:33 UTC, KS-KIM approved these changes

2020-08-27 07:28 UTC, taejinseok approved these changes
👍

2020-08-27 08:14 UTC, Ramen6315 approved these changes
👍

2020-08-27 10:38 UTC, kimevanjunseok approved these changes

2020-08-27 11:11 UTC, merged