feat(fullstack): 프로필 페이지 및 관련 기능 구현 (#192)
woowacourse-teams/2020-taggle pull request #193
Opened 2020-08-26 12:10 UTC by kimevanjunseok

resolve #192

2020-08-26 15:08 UTC, Ramen6315 requested changes
정말 많은 작업을 해주셨네요!
정말 고생 많으셨습니다.

궁금한점에 대해서 몇가지 리뷰 남겼습니다.
💯 💯 💯 💯

2020-08-26 15:08 UTC, Ramen6315 commented on backend/web/src/main/java/com/woowacourse/taggle/user/controller/UserController.java
> +    public ResponseEntity<SessionUser> getUserInfo(@AuthenticationPrincipal final SessionUser user) {
👍

2020-08-26 18:17 UTC, KS-KIM requested changes
리뷰할 부분이 광범위하게 퍼져있어 부득이하게 한 곳에 코멘트로 남깁니다.

1. 프로필 업데이트 API 관련 사항
사용자가 `알림 수신용 이메일 변경` 또는 `알림 설정여부 변경`할 때 두 가지 요청을 별도로 하도록 만드셨네요.
사용자의 수정사항 하나하나 API로 만들다보면 만들어야 할 API가 너무 많아지고 관리하기도 어려워 질 것 같아요.
단순하게 updateProfile 메서드 하나만 두고, `PUT /api/v1/users/{userId}` 꼴의 API를 만드는 것이 좋지 않을까요?
요청 dto도 `ProfileUpdateRequest` 하나로 만들고 엔티티로 변환 시 null인 필드를 제외하고 업데이트 하도록 만들 수 있으니 더 편할 것 같아요.
생각해보니, 이전에 작성한 API들도 위와 같이 작성되었다면 변경을 고려해보는게 좋을 것 같네요.

2. vuex에서 제공하는 메서드 호출 형태 변경
아래와 같이 변경 가능한 것으로 알고 있는데, 바꿔보는건 어떨까요?
(intellij에서는 제대로 잡지 못하지만 동작은 정상적으로 되더라구요)

e.g.
```javascript
// AS-IS
this[DELETE_USER]();
this[SHOW_SNACKBAR](MESSAGES.USER.DELETE.SUCCESS);

// TO-BE
this.deleteUser();
this.showSnackbar(MESSAGES.USER.DELETE.SUCCESS);
```

2020-08-26 18:17 UTC, KS-KIM commented on backend/web/src/docs/asciidoc/api-guide.adoc
> +=== 사용자 회원 탈퇴
사용자와 회원의 의미가 중첩적인 것 같아요.
'사용자'를 빼도 맥락상 문제가 없지 않을까요?

2020-08-26 18:17 UTC, KS-KIM commented on backend/web/src/main/java/com/woowacourse/taggle/user/controller/UserController.java
> +    @GetMapping("/user-info")
일반적으로 많이 사용하는 `/me`도 괜찮을 것 같아요.
절대로 `-`가 싫어서 그런건 아닙니다 :)

2020-08-26 18:17 UTC, KS-KIM commented on backend/web/src/test/java/com/woowacourse/taggle/user/controller/UserControllerTest.java
> +    }
⁉️

2020-08-27 01:28 UTC, ksy90101 commented on backend/core/src/main/java/com/woowacourse/taggle/user/service/UserService.java
>      public User findById(final Long id) {
find에서는 readOnly를 붙여주는게 좋겠군요~

2020-08-27 01:28 UTC, ksy90101 commented on backend/core/src/test/java/com/woowacourse/taggle/user/service/UserServiceTest.java
> +
!?

2020-08-27 01:32 UTC, ksy90101 commented on backend/web/src/frontend/src/store/modules/user.js
> +};
제 생각은 vuex에서는 try-catch로 잡을 필요가 없다고 생각해요. 예외를 던진다고 생각하여, 사용하는 곳에서 try-catch로 잡으면 될거 같습니다~

2020-08-27 01:33 UTC, ksy90101 commented on backend/web/src/main/java/com/woowacourse/taggle/user/controller/UserController.java
> +    @GetMapping("/user-info")
저도 me를 추천합니다~

2020-08-27 01:35 UTC, ksy90101 commented on backend/web/src/test/java/com/woowacourse/taggle/acceptance/UserAcceptanceTest.java
> +    void manageUser() {
흠.... 인수테스트가 완성이 되지 않은건가요? 아니면, 나머지는 할수 없어서 그런건가요? (수정, 탈퇴) 사용자 정보를 가져오는거 하나만 할거면, 없는게 나을거 같아요~

2020-08-27 01:35 UTC, ksy90101 commented on backend/web/src/test/java/com/woowacourse/taggle/user/controller/UserControllerTest.java
> +
@_@

2020-08-27 07:09 UTC, kimevanjunseok commented on backend/web/src/frontend/src/views/profile/ProfilePage.vue
> +      <h2 style="padding-top: inherit">{{ user.nickName }}</h2>
`inherit`는 vuetify에 없는 거 같습니다. 따로 빼겠습니다 😊😊

2020-08-27 07:12 UTC, kimevanjunseok commented on backend/web/src/main/resources/db/migration/V1__init.sql
> +SET foreign_key_checks = 1;
네 그렇습니다!!!!

2020-08-27 07:33 UTC, kimevanjunseok commented on backend/web/src/frontend/src/views/profile/ProfilePage.vue
> +    },
`onUpdateNotificationEnabled`안에 try/catch 설정해 놓으니 watch에서 안해도 잡더라구요!!! 그래서 안했습니다.

2020-08-27 07:35 UTC, kimevanjunseok commented on backend/web/src/test/java/com/woowacourse/taggle/acceptance/UserAcceptanceTest.java
> +    void manageUser() {
나중에 추가 될 것이나 리팩토링하면서 해결될 문제라면 그대로 두는 것이 좋다고 생각해서 할 수 있는 것까지 테스트 했습니다. 럿고 생각은 그래도 없는게 나을 것 같나요? 😭😭

2020-08-27 07:58 UTC, kimevanjunseok commented on backend/web/src/main/java/com/woowacourse/taggle/user/controller/UserController.java
> +    @GetMapping("/user-info")
다른 컨트롤러로 빼는 것은 나중에하고 `/me`로 수정하겠습니다!!!

2020-08-27 08:47 UTC, taejinseok approved these changes
고생 많으셨습니다! 
워낙 잘 만들어서 코멘트 남길만한게 많지 않았네요. 
다른 리뷰어들이랑 겹치지 않는 선에서 개인적인 생각 남겨놓았는데 
선택적으로 반영해주시면 될거같아요!

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/frontend/public/index.html
> +    <meta name="referrer" content="no-referrer">
👍

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/frontend/src/store/share/actionTypes.js
> +export const DELETE_USER = 'deleteUser';
하나의 actionTypes에서 여러 도메인관련 constants를 정의하고 사용하다보니 코드가 커지면 헷갈릴수도 있을거 같아요. 
일단은 주석을 통해 //user로 구분해봐도 좋을 것 같아요~

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/frontend/src/views/bookmark/components/CardIcons.vue
> -    </v-btn>
👍

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/frontend/src/views/main/MainPage.vue
> +      <BookmarkAddModal v-if="bookmarkAddModalEnabled()" />
아주 사소한건데 괄호를 뺀다면 동작 하나요? ㅎㅎㅎ 뭔가 이친구는  method 대신에 computed로 사용하는것도 괜찮을것 같네요!

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/frontend/src/views/profile/ProfilePage.vue
> +}
css... 👍

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/main/resources/db/migration/V1__init.sql
> +SET foreign_key_checks = 1;
알겠습니다!

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/test/java/com/woowacourse/taggle/acceptance/UserAcceptanceTest.java
> +    void manageUser() {
이부분은 ArgumentResolver에서 User를 mocking 해온걸 가져와서 수정 탈퇴를 테스트 하지 못한다 이야기 들었어요. 
현재로서는 인수테스트가 없는게 나아 보이긴 하네요.

2020-08-27 08:47 UTC, taejinseok commented on backend/web/src/test/java/com/woowacourse/taggle/user/controller/UserControllerTest.java
> +    @DisplayName("removeUser: 카테고리 하나를 제거한다.")
!

2020-08-27 12:06 UTC, kimevanjunseok commented on backend/web/src/frontend/src/views/main/MainPage.vue
> +      <BookmarkAddModal v-if="bookmarkAddModalEnabled()" />
DM 드렸습니다!!! 확인해 보세요!!!

2020-08-27 12:36 UTC, Ramen6315 approved these changes

2020-08-27 13:07 UTC, ksy90101 approved these changes

2020-08-27 15:59 UTC, KS-KIM approved these changes

2020-08-27 16:00 UTC, merged