feat(bookmarks): infinite scroll 적용 (#185)
woowacourse-teams/2020-taggle pull request #194
Opened 2020-08-26 15:17 UTC by KS-KIM

resolve #185 

infinite scroll 적용 완료하여 PR 날립니다.

북마크가 존재하지 않을 때 출력하는 페이지도 넣어놨습니다. 그런데 이미지 추가하면 레이아웃 꺠져서 일단은 텍스트만 보이도록 해놨습니다.

이 PR 머지한 후에 프론트에서 충돌나는 부분이 발생한다면 DM 부탁드립니다.

2020-08-26 15:19 UTC, KS-KIM commented on backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkFindRequest.java
> +    }
여기 리팩토링 예정입니다.

2020-08-26 17:13 UTC, Ramen6315 requested changes
구현 하느라 고생하셨습니다.

몇가지 궁금한점에 대해서 리뷰 남겼어요!.

리팩토링 하신다고 한 부분에 대해선 따로 남기지 않았습니다!

고생 많으셨습니다.

2020-08-26 17:13 UTC, Ramen6315 commented on backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkResponse.java
> +    public static List<BookmarkResponse> asList(final Collection<TagBookmark> bookmarks) {
Collection 으로 한 이유가 궁금해서 List로 변경해서 나온 에러를 찾아봤는데

Row Type이 동일한 모든 제네릭 타입은 컴파일된 시점에서 모두가 동일한 타입으로 존재하기 때문인가요??

배워가네요..

2020-08-26 18:25 UTC, KS-KIM commented on backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkResponse.java
> +    public static List<BookmarkResponse> asList(final Collection<TagBookmark> bookmarks) {
type erasure를 참고하시면 좋을 것 같네요 :)

2020-08-26 18:26 UTC, KS-KIM commented on backend/web/src/frontend/src/store/modules/tagWithBookmarks.js
> +    const res = await TagService.findBookmarksByTagId(tagId, start, display);
바빠서 신경을 못썼습니다... 레벨 3 끝나고 프론트쪽 예외처리 부족한부분을 한꺼번에 다듬는게 좋을 것 같아요.

2020-08-26 18:29 UTC, Ramen6315 commented on backend/web/src/frontend/src/store/modules/tagWithBookmarks.js
> +    const res = await TagService.findBookmarksByTagId(tagId, start, display);
이부분은 제가 프론트에 대해서 확실하게 파악 할겸 맡아서 해보고싶네요

2020-08-27 01:24 UTC, ksy90101 approved these changes
역시 👍 저는 간단한 피드백만 남겨놨습니다~
굳이 로직에서는 문제 될게 없는거 같네요! 고생하셨습니다~

2020-08-27 01:24 UTC, ksy90101 commented on backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkFindRequest.java
> +            throw new IllegalArgumentException("페이지 시작 위치가 올바르지 않습니다.");
지금까지 커스텀 예외를 만들었으니, 여기도 만들면 좋을거 같네요~

2020-08-27 01:24 UTC, ksy90101 commented on backend/core/src/test/java/com/woowacourse/taggle/tag/service/TagBookmarkServiceTest.java
> +        final BookmarkFindRequest bookmarkFindRequest = new BookmarkFindRequest(1, 24);
공통된 애는 빼는걸 추천합니다.

2020-08-27 01:24 UTC, ksy90101 commented on backend/core/src/main/java/com/woowacourse/taggle/tag/dto/BookmarkFindRequest.java
> +    private Integer display;
display보다 size라는 이름을 더 사용하는걸로 알고 있는데, 어떻게 생각하시나요!?

2020-08-27 01:24 UTC, ksy90101 commented on backend/web/src/frontend/src/store/modules/tagWithBookmarks.js
> +    const res = await TagService.findBookmarksByTagId(tagId, start, display);
vuex에서 try-catch로감싸야 할까요?
사용하는 부분에서 try-catch로 감싸면 되지 않을까요?
지금까지 그렇게 처리해왔습니다~ (예외를 던진다고생각하면 좋을거 같네요~)

2020-08-27 01:24 UTC, ksy90101 commented on backend/web/src/frontend/src/views/bookmark/BookmarkPage.vue
> +    async infiniteHandler($state) {
이 부분들을 try-catch로 감사는게 맞는거 같습니다~

2020-08-27 06:51 UTC, taejinseok commented on backend/web/src/frontend/src/store/modules/tagWithBookmarks.js
> +    const res = await TagService.findBookmarksByTagId(tagId, start, display);
지금까지는 럿고의견대로 vuex store actions에서는 별도로 try~catch문을 사용하지 않았어요. 
try~catch는 해당 vuex 코드 클라이언트가 처리하는게 맞다 생각했거든요.

2020-08-27 07:22 UTC, taejinseok approved these changes
고생하셨습니다. 
다른 분들이 웬만한 의견 제시해주셔서 별다른 코멘트는 남기지 않았습니다. 😀😀

2020-08-27 07:22 UTC, taejinseok commented on backend/core/src/test/java/com/woowacourse/taggle/tag/service/BookmarkServiceTest.java
> +        final BookmarkFindRequest bookmarkFindRequest = new BookmarkFindRequest(1, 24);
이제는 페이징을 활용하기 때문에 @DisplayName에 메서드 설명을 살짝 바꿔도 좋을것 같아요. 
전체 북마크 대신 페이징을 활용한다는 식으로요?

2020-08-27 07:29 UTC, kimevanjunseok approved these changes

2020-08-27 08:15 UTC, Ramen6315 approved these changes
👍

2020-08-27 08:34 UTC, merged