feat(docs): Rest docs 정적 파일을 생성하여 서버에 올린다. (#166)
woowacourse-teams/2020-taggle pull request #211
Opened 2020-09-02 14:56 UTC by Ramen6315

resolve #166

2020-09-03 03:18 UTC, ksy90101 requested changes
서브모듈쪽은 리뷰가 달라지 않아서 여기에 적어요.
올려주신 PR에서 prod가 create-drop으로 설정되어있어요. 
master를 바라보게 변경해주세요.
고생하셨습니다!

2020-09-03 03:18 UTC, ksy90101 commented on backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
> +                        .antMatchers("/docs/api-guide.html").hasRole("ADMIN")
컨트롤러에서는 /docs라고 주고 시큐리티에서는 docs/api-guide.html을 설정하셨네요!
하나로 통일하는게 좋을거 같아요~

2020-09-03 03:20 UTC, KS-KIM requested changes
간단한 리뷰 남겼습니다.

커밋 메시지는 조금 더 작업에 대해 명시적으로 써주시는게 좋을 것 같아요.

2020-09-03 03:20 UTC, KS-KIM commented on backend/web/build.gradle
> +    into file("src/main/resources/static/docs")
WebApplication을 실행할 때 자동으로 build가 진행되는데, test가 실행되지 않으니 docs 또한 만들어지지 않네요.
직접 gradle clean build시에는 docs가 생성되니 차라리 docs의 위치를 resources/templates에 옮기고 `asciidoctor.doFirst` 작업을 없애는건 어떨까요?

### WebApplication 실행시 진행되는 tasks
```
> Task :core:compileJava UP-TO-DATE
> Task :core:processResources UP-TO-DATE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :crawler-api:compileJava UP-TO-DATE
> Task :crawler-api:processResources NO-SOURCE
> Task :crawler-api:classes UP-TO-DATE
> Task :crawler-api:jar UP-TO-DATE
> Task :web:compileJava UP-TO-DATE
> Task :web:nodeSetup SKIPPED
> Task :web:npmSetup SKIPPED
> Task :web:npmInstall UP-TO-DATE
> Task :web:buildFrontend
> Task :web:processResources UP-TO-DATE
> Task :web:classes UP-TO-DATE
```

### gradle build시 진행되는 tasks
```
> Task :core:compileJava UP-TO-DATE
> Task :core:processResources UP-TO-DATE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :crawler-api:compileJava UP-TO-DATE
> Task :crawler-api:processResources NO-SOURCE
> Task :crawler-api:classes UP-TO-DATE
> Task :crawler-api:jar UP-TO-DATE
> Task :web:compileJava
> Task :web:nodeSetup SKIPPED
> Task :web:npmSetup SKIPPED
> Task :web:npmInstall UP-TO-DATE
> Task :web:buildFrontend
> Task :web:processResources
> Task :web:classes
> Task :web:compileTestJava
> Task :web:processTestResources
> Task :web:testClasses
> Task :web:test
> Task :web:asciidoctor
> Task :web:bootJar
> Task :web:jar SKIPPED
> Task :web:assemble
> Task :web:check
> Task :web:copyDocument
> Task :web:build
```

2020-09-03 03:20 UTC, KS-KIM commented on backend/web/src/main/java/com/woowacourse/taggle/HomeController.java
> +
redirect할 필요가 없지 않나요?

2020-09-03 03:20 UTC, KS-KIM commented on backend/web/src/main/java/com/woowacourse/taggle/security/config/WebSecurityConfig.java
> +                        .antMatchers("/docs/api-guide.html").hasRole("ADMIN")
```suggestion
                        .antMatchers("/docs/**").hasRole("ADMIN")
```
이렇게 하는게 낫지 않을까요?

2020-09-03 03:46 UTC, ksy90101 commented on backend/web/build.gradle
> +    into file("src/main/resources/static/docs")
templates에 대해 간단하게 이야기 적을게요!
Static파일이란 웹 사이트 구성요소 중 Image, CSS, Script파일과 같이 그 내용이 고정되어 응답을 할 때 별도의 처리 없이 파일 내용을 그대로 보내주면 되는 파일을 의미합니다.
따라서 docs의 html 파일을 templates가 아닌 static 폴더에 넣는것 같습니다
공식 문성에서도 static에 넣는 예제가 있습니다!
https://docs.spring.io/spring-restdocs/docs/2.0.4.RELEASE/reference/html5/#getting-started-build-configuration-packaging-the-documentation

지금 테스트를 해보니 템플릿 엔진이 없어도 정적 파일이여서 해당 HTML이 실행이 됩니다.
따라서 templates에 넣는 것은 안맞다고 생각해요!
다른분들의 생각이 궁금하네요~

2020-09-03 04:36 UTC, kimevanjunseok approved these changes
라면 고생하셨습니다!!!
간단히 남겨드렸습니다😊😊

2020-09-03 04:36 UTC, kimevanjunseok commented on backend/web/src/docs/asciidoc/api-guide.adoc
> +==== Example Request
전에 있던 docs에서 `Example Request` , `Examplme Response`가 있던 이유는 
```
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response
```
이렇게 위에서 설정했기 때문입니다. 
그대로 따라가도 상관없지만 원래 http-request와 http-response에 대한 정보를 나타내고 있는 것인데 꼭 현재처럼은 할 필요없다는 것을 말하고 싶어서 리뷰 남겨드립니다.
만약 그대로 진행하신다면 위의 설정은 지우셔도 될 것 같습니다😊😊

2020-09-03 04:39 UTC, KS-KIM commented on backend/web/build.gradle
> +    into file("src/main/resources/static/docs")
api-guide.html이 템플릿 엔진에 의해 동적으로 생성되지 않아 static 폴더에 넣는다면 현재 templates에 위치한 index.html 역시 static으로 이동하는게 맞다고 생각하는데, 어떻게 생각하시나요? 그러면 thymeleaf 의존성을 가질 필요도 없겠네요.

2020-09-03 04:43 UTC, ksy90101 commented on backend/web/build.gradle
> +    into file("src/main/resources/static/docs")
오호 그거까지는 생각을 못햇는데 역시 앞서 나가시는 알트형님 👍 
https://eastgyu.github.io/spring/Spring-Vue/
아래 링크를 참고해도 그렇네요~

2020-09-03 12:19 UTC, Ramen6315 commented on backend/web/build.gradle
> +    into file("src/main/resources/static/docs")
@KS-KIM @ksy90101 static에서 api-guide.html을 생성하면서 궁금했던 부분중 하나였는데 의견 중 
`'Static파일이란 웹 사이트 구성요소 중 Image, CSS, Script파일과 같이 그 내용이 고정되어 응답을 할 때 별도의 처리 없이 파일 내용을 그대로 보내주면 되는 파일을 의미합니다.'`
이부분을 보니까 templates에 위치한 index.html도 static으로 옮기는게 맞지 않을까? 하는생각이 들었어요!

그런데 thymeleaf에 대해서 정확하게 파악이 안되서 이것저것 찾아보다가 의문이 들었던게

`현재 templates에 위치한 index.html 역시 static으로 이동하는게 맞다고 생각하는데, 어떻게 생각하시나요? 그러면 thymeleaf 의존성을 가질 필요도 없겠네요.`
이 의미가 템플릿 엔진으로 thymeleaf를 사용하고 있는데 templates에 Index.html이 static으로 옮겨진다면 templates에 아무 것도 없으니까 thymeleaf를 사용할 필요가 없다는건가요??
그렇다면 
`Thymeleaf는 html파일을 가져와서 파싱해서 분석후 정해진 위치에 데이터를 치환해서 웹 페이지를 생성합니다.`
라는 글을 읽었는데 그렇다면
templates에 있는 index.html 을 static으로 옮기고 thymeleaf에 대한 의존성을 제거 하는것만 으로 괜찮은건지
아니면 다른 추가 작업이 필요한건지 궁금해요!

2020-09-03 12:31 UTC, Ramen6315 commented on backend/web/src/main/java/com/woowacourse/taggle/HomeController.java
> +
처음에는 "/docs/api-guide.html" url이 있기 때문에 굳이 할 필요가 없다고 생각이 들었었는데

문서화 페이지도 하나의 페이지기도 하고 /docs/api-guide.html의  url이 코드 안에서 표현되는 곳이 아직 없다고 생각했기 때문에 이를 controller를 통해 알고 있어야 하지 않을까? 라고 생각이 들어서 

일단 적어놓고 리뷰를 통해서 수정을 할 생각으로 작성 했습니다.

그래서 /docs/api-guide.html이 일단 하나의 페이지로 만들어져 있으니 getmapping을 하고 return 으로 redirect 해줘야 겠다고 생각했습니다!

2020-09-03 12:38 UTC, KS-KIM commented on backend/web/build.gradle
> +    into file("src/main/resources/static/docs")
템플릿 엔진을 사용하여 서버사이드 렌더링을 하지 않기 때문에 thymeleaf의 역할이 없습니다. 사실 원래부터 필요없었어요.

말씀하신대로 index파일 생성 경로를 static으로 옮기고 (vue config 파일에 index파일 관련 설정이 있는데, 그것만 지우면 빌드시 index파일이 static에 위치하게 될겁니다) 의존성을 제거하면 될 것 같습니다.

2020-09-03 20:32 UTC, Ramen6315 commented on backend/web/src/docs/asciidoc/api-guide.adoc
> +==== Example Request
기존 형태로 merge가 됐기 때문에 기존 형태를 최대한 따라가는것이 맞다고 생각했습니다!

```
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response
```
이 두개는 삭제 해야겠네요 !

2020-09-03 20:33 UTC, Ramen6315 commented on backend/web/src/main/java/com/woowacourse/taggle/HomeController.java
> +
이 부분에 대해서는 의견 종합후 결정 되는대로 삭제를 하던지 수정을 하던지 하는게 맞는거 같아요!

2020-09-05 08:06 UTC, KS-KIM approved these changes
피드백 반영 잘하셨습니다💯💯
이만 approve 할게요

2020-09-05 08:10 UTC, taejinseok approved these changes
오랫 동안 고생하셨습니다!

2020-09-05 08:54 UTC, ksy90101 approved these changes

2020-09-05 08:56 UTC, merged