refactor(backend): Spring Security 권한 재설정 (#223)
woowacourse-teams/2020-taggle pull request #235
Opened 2020-09-10 12:43 UTC by Ramen6315

resolve #233

2020-09-10 16:51 UTC, KS-KIM requested changes
간단한 리뷰 남겼습니다.

2020-09-10 16:51 UTC, KS-KIM commented on backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
> +        webSecurity.ignoring().antMatchers("/taggle-favicon.ico", "/img/**");
안그래도 처리했어야 하는 부분인데 잘하셨어요 💯💯

2020-09-10 16:51 UTC, KS-KIM commented on backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
> +                        .antMatchers("/", "/signin", "/login/**", "/h2-console/**", "/css/**", "/img/**", "/js/**", "/api/v1/users/me").permitAll()
```suggestion
                        .antMatchers("/", "/signin", "/h2-console/**", "/css/**", "/img/**", "/js/**", "/api/v1/users/me").permitAll()
```
자체적인 로그인 페이지를 사용하니 /login 접근 권한은 없어도 무방할 것 같아요

2020-09-10 16:51 UTC, KS-KIM commented on backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
> +                        .antMatchers(  "/fonts/**", "/api/**","/taggle-favicon.ico").hasRole("USER")
폰트가 USER에게만 제공되어야 할 이유가 있나요?

2020-09-10 22:56 UTC, taejinseok approved these changes
의견 및 궁금한 것 남겨 놓았습니다. 고생하셨습니다.

2020-09-10 22:56 UTC, taejinseok commented on backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
> +                        .antMatchers(  "/fonts/**", "/api/**","/taggle-favicon.ico").hasRole("USER")
같은 맥락에서 favicon또한 모두에게 제공되는게맞지 않을까요?

2020-09-10 22:56 UTC, taejinseok commented on backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
> +                        .antMatchers(  "/fonts/**", "/api/**","/taggle-favicon.ico").hasRole("USER")
정적 자원들은 WebSecurity타입을 인자로 받는 configure 메서드에서 ignoring 전략을 활용하기로 한걸로 알고 있는데, 이곳에서도 정적 자원들에 대한 권한 설정을 하는 이유가 있을까요?

2020-09-11 01:38 UTC, ksy90101 approved these changes
다른분들이 제가 하고싶은 리뷰를 했네요! 그것만 하면 될거 같습니다~
고생하셧습니다!

2020-09-11 01:45 UTC, kimevanjunseok approved these changes

2020-09-11 07:54 UTC, Ramen6315 commented on backend/taggle-web/src/main/java/kr/taggle/security/config/WebSecurityConfig.java
> +                        .antMatchers(  "/fonts/**", "/api/**","/taggle-favicon.ico").hasRole("USER")
이부분은 제가 삭제를 했어야 했는데 실수로 안했네요 

삭제 했고 작동하는것 확인 했습니다!

2020-09-11 08:57 UTC, KS-KIM approved these changes
리뷰 남긴 부분은 다 반영하셔서 approve 하겠습니다.

공백문자 수정한 커밋은 `style` 헤더가 더 맞는 것 같으니 차후에 참고하시면 좋을 것 같아요.

2020-09-11 09:00 UTC, merged