feat: 비즈니스 검증 로직 추가 (#227)
woowacourse-teams/2020-taggle pull request #247
Opened 2020-09-16 06:18 UTC by kimevanjunseok

resolve #227 

tag 입력은 validate는 적용되지만 rules에 의한 경고창은 적용이 안됩니다. 이유는 태그가 추가되야 잘못된 입력인 것을 알려주는 데 현재 잘못된 입력은 추가가 되지 않기 때문에 경고문을 명시적으로 알려줄 수 없습니다.
기능을 구현하기위해 tag 입력부분 코드가 더러울 수 있습니다. 참고하시고 궁금한 것은 물어봐 주세용!!!

2020-09-16 13:46 UTC, KS-KIM reviewed
간단한 리뷰 남겼습니다.

따로 적을 곳이 없어서 한가지 의견 더 남깁니다. Spring Validation이 적용된 객체도 테스트의 대상이 아닐까요?

테스트 하는 방법이 구글링하면 나오니 해보는게 좋을 것 같아요.

2020-09-16 13:46 UTC, KS-KIM commented on backend/taggle-core/build.gradle
> +    implementation 'org.springframework:spring-webmvc:5.2.7.RELEASE'
이 의존성은 web과 관련된 의존성인데 비즈니스 로직을 다루는 core 모듈에 있는게 맞을까요? spring boot starter에 포함되어 있는 의존성이기에 여기에 둘 필요가 없어보여요. WebMvcConfigurer를 위해 추가한 것 같은데, WebMvcConfigurer를 web 모듈로 옮기는게 좋을 것 같아요.

2020-09-16 13:46 UTC, KS-KIM commented on backend/taggle-core/src/main/java/kr/taggle/common/config/ValidationMessageConfig.java
> +}
위에 말씀드린 바와 같이 이 클래스를 core 모듈에 둘 것이 아니라, web모듈에 두는 편이 맞을 것 같아요.
옮기고 빌드 돌려본 결과 테스트는 문제 없이 작동하네요.

2020-09-16 13:58 UTC, KS-KIM reviewed
로컬에서 WebApplication 실행시 SQL문 식별문제로 에러가 발생하니 이 부분까지 해결해야 할 것 같아요.
MODIFY문을 인식 못하나봐요.

2020-09-16 14:16 UTC, kimevanjunseok reviewed
@KS-KIM 혹시 서브모듈 풀 받으셨나요? 안 받으셨다면 설정때문에 받으셔야합니다😂😂

2020-09-16 17:29 UTC, Ramen6315 approved these changes
궁금한것에 대해서 리뷰 남겼습니다.
그 이외에는 잘 구현해주신거 같아 approve 하겠습니다.!

2020-09-16 17:29 UTC, Ramen6315 commented on backend/taggle-web/build.gradle
> +    implementation 'net.rakugakibox.util:yaml-resource-bundle:1.1'
단순한 궁금증입니다!
64 line은 yml 파일 에서 message 설정이라고 알았는데
spring-webmvc는 왜 추가 되었나요???

2020-09-17 06:39 UTC, ksy90101 approved these changes
고생하셨습니다~
한가지만 다같이 논의하면 좋을만 한게, 프론트에서 예외 메시지를 동사로 하는게 더 좋을지 아니면 지금처럼 가는게 더 좋을지를 고민해봐야 할거 같네요~ 수고하셨습니다!

2020-09-17 06:51 UTC, ksy90101 commented on frontend/src/utils/validator.js
> +      (v) => v.length <= 25 || '25자보다 길수 없음.',
프론트에서 예외메시지는 동사로 가져가면 좋을거 같아요.
여기뿐만 아니라 전체다요 ㅎㅎ 
고생해주십쇼 ㅎ ㅎ

2020-09-17 07:05 UTC, kimevanjunseok commented on backend/taggle-web/build.gradle
> +    implementation 'net.rakugakibox.util:yaml-resource-bundle:1.1'
앗 같이 옮겨 보렸네요. 수정하겠습니다.

2020-09-17 08:57 UTC, taejinseok requested changes
고생하셨습니다. 
간단한 코멘트 남겨놓았으니 확인 부탁드려요!

2020-09-17 08:57 UTC, taejinseok commented on backend/taggle-web/build.gradle
> +    implementation 'org.springframework:spring-webmvc:5.2.7.RELEASE'
스프링 부트 의존성에 webmvc가 포함되어있는 것으로 알고있습니다! 
해당 의존성 제거후에도 `WebMvcConfigurer ` 관련 해서 메시지 검증이 의도대로 동작함을 확인할 수 있었어요! 
따라서 이 의존성은 제거해도 무방해 보입니다.

2020-09-17 08:57 UTC, taejinseok commented on backend/taggle-core/src/main/resources/messages.yml
> +    name: 태그는 25자보다 클 수 없습니다.
지금와서 보는데...  예외상황에 대한 테스트 코드들이 빠져있네요 ! 지금 당장은 아니더라도 이슈로 등록하고 예외 테스트에 대해서도 고려해보면 좋겠네요!

2020-09-17 08:57 UTC, taejinseok commented on frontend/src/views/main/component/BookmarkAddModal.vue
> +        }
UI가 훨씬 예뻐졌네요! 👍 
페이지 우측에 개별 북마크 수정 버튼을 누를때 나타나는 태그 편집 다이아로그 창은 예전 UI로 그대로 사용되고 있어요. 
`frontend/src/views/bookmark/component/TagEditModal.vue`  확인 부탁 드립니다! 
(이부분은 코드가 중복이 발생하고 있는데,  mixin을 활용하는 것도 고려해볼만 할것 같아요.)

https://kr.vuejs.org/v2/guide/mixins.html

2020-09-17 08:57 UTC, taejinseok commented on backend/taggle-core/src/main/resources/messages.yml
> +    name: 태그는 25자보다 클 수 없습니다.
검증실패시 메시지가 제대로 나타나는지 확인하는 과정에서 예외 상황에 대한 테스트 코드들이 누락되어있는 것을 확인했습니다!
이부분은 지금 테스트코드를 추가 vs 다음 이슈로 따로 고려 
두가지로 고려해보면 좋을것 같네요

2020-09-17 08:57 UTC, taejinseok commented on backend/taggle-web/build.gradle
> +    implementation 'org.springframework:spring-webmvc:5.2.7.RELEASE'
spring-boots-starter-web 의존성 안에  spring-webmvc 의존성이 포함되어있는 것으로 알고 있어요! 
해당 의존성을 없앤 뒤에 정상적으로 실행되는 것 확인했는데요. 확인 부탁드려요!

2020-09-17 12:00 UTC, taejinseok commented on backend/taggle-core/src/main/resources/messages.yml
> +    name: 태그는 25자보다 클 수 없습니다.
위에서 알트가 같은 의견을 남겨놓았네요!

2020-09-17 12:29 UTC, kimevanjunseok commented on backend/taggle-web/build.gradle
> +    implementation 'org.springframework:spring-webmvc:5.2.7.RELEASE'
확인했습니다!! 감사합니다!!😊😊

2020-09-17 23:44 UTC, KS-KIM approved these changes
validate 관련 테스트 코드만 추가하면 될 것 같아요.

여건이 되신다면 바로 리뷰 반영해주셨으면 좋겠고, 아니라면 이슈 등록해주세요.

2020-09-20 09:14 UTC, kimevanjunseok reviewed
테스트를 하면서 생각해 본 것들을 간단히 적어봅니다.

1. 지금 길이만 검증하고 있는 데 그 밖의 다른 검증들도 전부 메시지 담고, test 추가?
2. 컨트롤러에서 에러 메시지 검증이 가능한데 DTO TEST도 따로? DTO에서도 TEST하는 방법이 있습니다.
짧게 생각 했지만 현재는 컨트롤러만 검증하고 있습니다. 

그리고 vuetify 적용은 했고, 동글의 의견인 mixin은 못 한 상태입니다. 말 그대로 중복코드가 발생하여 줄여보려 했지만 아직 해결 못하고있고 이슈로 남기려고 합니다.

2020-09-21 04:54 UTC, taejinseok approved these changes
추가적인 코멘트 남겨놓았습니다! 
선택적으로 반영해주세요!

2020-09-21 04:54 UTC, taejinseok commented on backend/taggle-web/src/main/java/kr/taggle/common/controller/ApiControllerAdvice.java
> +        log.error(exception.getMessage());
error 로그는 예기치 못한 내부적린 에러 (500코드 반환 하는 그 예외에 해당하는 에러들!)를 보여주고 그외에 핸들링 할 수 있는 예외들은 info 로그로 남기는거 아니었나요?! 

InvalidURLException은 클라이언트의 잘못된 요청에 대한 예외로 핸들링할수 있는 예외라 생각듭니다!

2020-09-21 04:54 UTC, taejinseok commented on backend/taggle-web/src/test/java/kr/taggle/ControllerTest.java
> +    public void validateWhenPostRequest(final User user, final String uri, final String jsonParams, final ResultMatcher expect) throws
요청 바디 메시지에 대해 400 Bad Request를 expect 하는 테스트인데 `validateWhenPostRequest` 메서드명이 다소 추상적이라는 느낌이 드네요. 
BadRequest를 확인한다는 느낌의 메소드명은 어떤가요? 
`expectBadRequest` 같은 느낌으로요!

2020-09-21 04:54 UTC, taejinseok commented on backend/taggle-web/src/test/java/kr/taggle/category/controller/CategoryControllerTest.java
> +
마찬가지로 보다 구체적인 메서드 네이밍을 가져가면 좋을 것 같습니다!

2020-09-21 04:54 UTC, taejinseok commented on backend/taggle-web/src/test/java/kr/taggle/tag/controller/TagControllerTest.java
> +
마찬가지로 보다 구체적인 메서드 네이밍을 가져가면 좋을 것 같습니다!

2020-09-21 05:01 UTC, taejinseok commented
> 2\. 검증하고

1. 견고한 테스트를 위해서라면 메시지 길이 외 모든 경우를 테스트에 넣는 것이 좋겠네요. 많으면 많을 수록 좋다 생각합니다. 
2. 가장 이상적인 것은 DTO, 컨트롤러 모두 테스트 추가하는 것아닐까요?  컨트롤러테스트는 http 상태 코드와 body 값을 테스트, dto테스트는 예외 발생 여부를 테스트할 것이에요. 같은 내용을 테스트하더라도 두 테스트는 테스트 하고자하는 `맥락` 이 다르다 생각이 듭니다.  

우선은 이번 이슈는 글자 길이에 대한 컨트롤러 테스트까지만 처리하고 이 외의 케이스는 팀의견을 모은 뒤 별도로 이슈를 추가해서 처리하면 좋을 것 같습니다.

2020-09-21 05:02 UTC, kimevanjunseok commented on backend/taggle-web/src/main/java/kr/taggle/common/controller/ApiControllerAdvice.java
> +        log.error(exception.getMessage());
복붙의 흔적입니다... 해당 메서드는 `MethodArgumentNotValidException`로 네이밍 하였고 `log.info`로 수정하였습니다.

2020-09-21 05:05 UTC, kimevanjunseok commented on backend/taggle-web/src/test/java/kr/taggle/ControllerTest.java
> +    public void validateWhenPostRequest(final User user, final String uri, final String jsonParams, final ResultMatcher expect) throws
맞습니다. 저도 네이밍으로 고민 많이 했습니다 😂😂 그래서 문서에 있는 네이밍을 참고해서 작성하였는데... 생각해보니 추상적이네요. 하지만 `expectBadRequest` 마찬가지로 `BadRequest`를 기대하긴 하지만 어떤 상황?에서 `BadRequest`인지 명시하고 있지 않기 때문에 추상적인 느낌이 듭니다😂😂

2020-09-21 05:08 UTC, kimevanjunseok commented on backend/taggle-web/src/test/java/kr/taggle/ControllerTest.java
> +    public void validateWhenPostRequest(final User user, final String uri, final String jsonParams, final ResultMatcher expect) throws
`expectBadRequestWhenPostRequest`이건 어떨까요?

2020-09-21 05:21 UTC, kimevanjunseok reviewed
같은 생각입니다. 테스트 추가는 이슈로 남기고 리팩토링하는 것이 좋을 것 같습니다. 현재 태그 관련 UI도 붙잡고 있으니 여기까지 마무리 하겠습니다😊😊

2020-09-21 07:25 UTC, KS-KIM approved these changes
나머지분들이 리뷰 잘 해주셔서 approve 하겠습니다.

![image](https://user-images.githubusercontent.com/20358042/93741256-05d52400-fc27-11ea-8ea5-f4c0552466ea.png)

여전히 커밋명이 잘 지켜지지 않는 경우가 있는데, 신경 써주시면 좋겠어요..이거 습관입니다.

2020-09-21 15:07 UTC, merged